data:
  raw_data1: "data/raw/case_study1.xlsx"
  raw_data2: "data/raw/case_study2.xlsx"
  processed_data: "data/processed/merged_data.csv"
  encoded_data: "data/processed/encoded_data.csv"

model:
  save_path: "models/classifier.pkl"